# NumPy Assignment

In this assignment, you'll continue to familiarize yourself with the **NumPy** library, focusing on basic array arithmetic, matrix multiplication, and common aggregation functions.

You are to only write/modify the code in between consecutive `# < START >` and `# < END >` comments. **DO NOT modify other parts of the notebook.**

```python
"Don't modify any code here"

# < START >
"YOUR CODE GOES HERE!"
# < END >

"Don't modify any code here"
```

**Start by running the below cell, to ensure the NumPy library is imported.**

In [10]:
import numpy as np

## **1. Initializing Specific Arrays**

### **1.1 Specific Matrix**
- Initialize a numpy array `arr` with dimensions $2 × 3$ identical to $\begin{bmatrix} 1 & 2 & 5\\ 7 & 18 & 9 \end{bmatrix}$


In [11]:
# < START >

# < END >

print(arr)
print("Shape:", arr.shape)


[[ 1  2  5]
 [ 7 18  9]]
Shape: (2, 3)


Shape is an useful array property that tells us about the dimensions of the array and can be useful in debugging. There are several such properties about which you read.

### **1.2 Array with Random Values**
- Initialize a numpy array `x` of dimensions `2*3` with random values.

In [12]:
n_rows = 2
n_cols = 3

# < START >

# < END >

print("Random Array:", x)

Random Array: [[0.30058606 0.25194705 0.37634029]
 [0.86086527 0.93850145 0.29208533]]


### **1.3 Other methods**

In [13]:
#  Initialize an array I_4 like identity matrix
#  Initialize an array zero_223 with dimension 2*2*3 having all values as zero
#  Initialize an array one_54 with dimension 5*4 having all values as one

# < START >

# < END >

print("I_4:\n", I_4)
print("zero_23:\n", zero_23)
print("one_54:\n", one_54)

I_4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
zero_23:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
one_54:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


You can also transpose arrays (same as with matrices), but a more general and commonly used function is the `array.reshape()` function.
$$
\begin{bmatrix}
a & d\\
b & e\\
c & f
\end{bmatrix}
\xleftarrow{\text{.T}}
\begin{bmatrix}
a & b & c\\
d & e & f
\end{bmatrix}
\xrightarrow{\text{.reshape(3, 2)}}
\begin{bmatrix}
a & b\\
c & d\\
e & f
\end{bmatrix}
\xrightarrow{\text{.reshape(6,1)}}
\begin{bmatrix}
a\\b\\c\\d\\e\\f
\end{bmatrix}
$$

In [14]:
y = np.array([[1, 2, 3],
              [4, 5, 6]])

# < START >
# Create a new array y_transpose that is the transpose of matrix y

# < END >

print(y_transpose)

# < START >
# Create a new array y_flat that contains the same elements as y but has been flattened to a column array

# < END >

print(y_flat)

[[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## **2. Indexing and slicing**
Just like with normal arrays, you can access an element at the (i,j) position using `array[i][j]`.
However, NumPy allows you to do the same using `array[i, j]`, and this form is more efficient and simpler to use.

Slicing is another important feature of numpy arrays. The syntax is same as of python lists. i.e.

`sliced_array = array[start:end:step]`

In [15]:

x = np.array([1, 2, 3, 4, 5, 6, 7])

# <START>
# Create a new array y with the middle 3 elements of x

# <END>

print(y)

z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# <START>
# Create a new array w with alternating elements of z

# <END>

print(w)

[3 4 5]
[1 3 5 7 9]


A combination of indexing and slicing can also be used

In [16]:
arr_2d = np.array([[4, 5, 2],
          [3, 7, 9],
          [1, 4, 5],
          [6, 6, 1]])

# <START>
# Create a 2D array sliced_arr_2d that is of the form [[5, 2], [7, 9], [4, 5]]

# <END>

print(sliced_arr_2d)

[[5 2]
 [7 9]
 [4 5]]


## **3. Basic Array Arithmetic and Broadcasting**

### **3.1 Element-wise Operations**
- Given two arrays `A` and `B` of the same shape, perform the following element-wise operations and assign the results to the specified variables:
    * `C = A + B`
    * `D = A / B`

In [17]:
A = np.array([[10, 20], [30, 40]])
B = np.array([[2, 4], [5, 8]])

# < START >

# < END >

print("A + B (C):\n", C)
print("A / B (D):\n", D)

A + B (C):
 [[12 24]
 [35 48]]
A / B (D):
 [[5. 5.]
 [6. 5.]]


### **3.2 Broadcasting**
This is a great feature of numpy arrays. To learn more about it: [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)

In [18]:
arr1 = np.array([1, 2, 3, 4])
b = 1

# <START>
# Implement broadcasting to add b to each element of arr1

# <END>

print(arr1)

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr3 = np.array([[4],
                 [5]])

# <START>
# Multiply each element of the first row of arr2 by 4 and each element of the second row by 5, using only arr2 and arr3

# <END>

print(arr2)

[2 3 4 5]
[[ 4  8 12]
 [20 25 30]]


## **4. Matrix Multiplication (Dot Product)**

Matrix multiplication is a cornerstone of linear algebra and machine learning. In NumPy, this is achieved using the `np.dot()` function or the specialized `@` operator.

- Given a $2\times3$ matrix `M` and a $3\times2$ matrix `N`, calculate their matrix product `P = M @ N`.

$$\begin{aligned} M &= \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix} \\ N &= \begin{bmatrix} 7 & 8 \\ 9 & 10 \\ 11 & 12 \end{bmatrix}\end{aligned}$$

In [19]:
M = np.array([[1, 2, 3], [4, 5, 6]])
N = np.array([[7, 8], [9, 10], [11, 12]])

# < START >

# < END >

print("M @ N (P):\n", P)
assert P.shape == (2, 2)

M @ N (P):
 [[ 58  64]
 [139 154]]


## **5. Aggregation Functions**

NumPy provides powerful functions for calculating statistical values across arrays. These can be applied to the entire array or along a specified **axis**.

### **5.1 Global Aggregations**
- Calculate the **sum** of all elements in array `Q` and the **maximum** element.

In [20]:
Q = np.array([[10, 50, 2], [1, 99, 15]])

# < START >

# < END >

print("Total Sum of Q:", Q_sum)
print("Maximum value in Q:", Q_max)

Total Sum of Q: 177
Maximum value in Q: 99


### **5.2 Aggregations Along an Axis**
- Calculate the **mean** (average) of array `Q` **along the rows** (axis 0) and assign it to `Q_mean_rows`.
- Calculate the **minimum** value of array `Q` **along the columns** (axis 1) and assign it to `Q_min_cols`.

**Visualizing the Axes:**
* **Axis 0 (Rows):** Compresses the rows (vertical operation), resulting in a single value per column.
* **Axis 1 (Columns):** Compresses the columns (horizontal operation), resulting in a single value per row.

In [21]:
Q = np.array([[10, 50, 2], [1, 99, 15]])

# < START >

# < END >

print("Mean along Rows (axis=0):\n", Q_mean_rows)
print("Minimum along Columns (axis=1):\n", Q_min_cols)
assert Q_mean_rows.shape == (3,)
assert Q_min_cols.shape == (2,)

Mean along Rows (axis=0):
 [ 5.5 74.5  8.5]
Minimum along Columns (axis=1):
 [2 1]


## **6. Vectorization**
From what we've covered so far, you might be covering why are we using this vectorized approach. So, let's compare the execution time of both of these approaches.

Your goal is to multiply each element of the 2D array by 3.

In [22]:
import time

arr_nonvectorized = np.random.rand(1000, 1000)
arr_vectorized = np.array(arr_nonvectorized) # making a deep copy of the array

start_nv = time.time()

# Non-vectorized approach
# <START>

# <END>

end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000*(end_nv-start_nv), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
# print(arr_nonvectorized)

start_v = time.time()

# Vectorized approach
# <START>

# <END>

end_v = time.time()
print("Time taken in vectorized approach:", 1000*(end_v-start_v), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
# print(arr_vectorized)

Time taken in non-vectorized approach: 166.1362648010254 ms
Time taken in vectorized approach: 1.1167526245117188 ms
